In [4]:
# importing utilities
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets

In [7]:
# importing dataset
wine = datasets.load_wine()

In [9]:
X = wine.data
y = wine.target

X.shape

(178, 13)

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.6)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_p = model.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [32]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_p))

print(classification_report(y_test, y_p))

[[33  1  0]
 [ 4 39  1]
 [ 0  0 29]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        34
           1       0.97      0.89      0.93        44
           2       0.97      1.00      0.98        29

    accuracy                           0.94       107
   macro avg       0.94      0.95      0.95       107
weighted avg       0.95      0.94      0.94       107

