In [1]:
# importing utilities
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets

In [4]:
# import data
digits = datasets.load_digits(n_class = 10)
X = digits.data
y = digits.target
n_sample, n_features = X.shape
X.shape

(1797, 64)

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.8)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_p = model.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [13]:
from sklearn.metrics import confusion_matrix, classification_report

print(f' confusion matrix = {confusion_matrix(y_test, y_p)}')
print(f' classification report = {classification_report(y_test, y_p)}')

 confusion matrix = [[137   0   0   0   1   0   0   0   0   0]
 [  0 135   3   0   2   1   1   0   7   0]
 [  0   0 135   0   0   0   0   0   0   0]
 [  0   0   2 137   0   6   0   1   3   2]
 [  0   0   0   0 140   0   1   0   3   1]
 [  1   0   0   0   0 144   1   0   0   2]
 [  0   2   0   0   1   0 133   0   0   0]
 [  0   0   0   0   1   1   0 145   0   2]
 [  0  26   2   1   0   1   2   1 107   3]
 [  0   0   0   7   1   0   0   0   4 132]]
 classification report =               precision    recall  f1-score   support

           0       0.99      0.99      0.99       138
           1       0.83      0.91      0.87       149
           2       0.95      1.00      0.97       135
           3       0.94      0.91      0.93       151
           4       0.96      0.97      0.96       145
           5       0.94      0.97      0.96       148
           6       0.96      0.98      0.97       136
           7       0.99      0.97      0.98       149
           8       0.86      0.75    