#DEMONSTRATE HOW LINEAR ALGEBRA AND OTHER STATS OPERATIONS ARE IMPLEMENTED USING NUMPY

In [2]:
import numpy as np;

In [3]:
A_3_5 = np.arange(15).reshape((3,5)) ; A_3_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##Transposing the Array using the *T* attribute

In [4]:
A_3_5.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
A_3_5.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

##Inner Matrix Product van be calculated by any of the below methods:-

*   np.dot() method
*   @



In [6]:
A_6_3 = np.random.randn(6,3)

In [7]:
A_3_6 = np.random.randn(3,6)

In [8]:
#Multiply the matrix
np.dot(A_3_6,A_6_3)

array([[-1.39758438, -1.06951009,  2.02915456],
       [ 2.14765923,  2.37193865, -1.71784286],
       [ 0.34766322, -1.78625603, -1.02640981]])

In [9]:
#Multiply the matrix
A_3_6 @ A_6_3

array([[-1.39758438, -1.06951009,  2.02915456],
       [ 2.14765923,  2.37193865, -1.71784286],
       [ 0.34766322, -1.78625603, -1.02640981]])

##Compute INVERSE OF a MATRIX using 

*   np.linalg.inv() method



In [10]:
A_5_5 = np.random.randn(5,5) ; A_5_5

array([[ 1.47420964,  0.83924072, -0.37336442, -1.09254894,  0.59284664],
       [ 0.21735037,  0.29448827, -0.57174474,  0.2419013 , -0.5382392 ],
       [-0.75610559, -0.20742045,  0.50695644, -2.15991804,  0.3212748 ],
       [ 0.2922212 , -0.52198437,  0.87792964,  0.3065737 ,  1.83794833],
       [ 0.93670838, -0.78650806,  0.78762775,  0.30912925,  0.47141438]])

In [11]:
#Inverse of the matrix
np.linalg.inv(A_5_5)

array([[ 0.30081298,  0.23699381, -0.07136185, -0.15072531,  0.52857   ],
       [ 0.94490174, -5.27805244, -1.4004403 , -1.35698881, -0.96949748],
       [ 0.65773693, -6.16220434, -1.28704815, -1.76800816, -0.09264307],
       [-0.05424975, -0.79349592, -0.5577853 , -0.0771917 , -0.1566607 ],
       [-0.08460259,  1.5391789 ,  0.3214375 ,  1.04005638, -0.28899602]])

#Compute QR Decomposition of the Matrix.

*   np.linalg.qr() method.





In [12]:
#Compute QR Decoposition of the matrix.
q, r = np.linalg.qr(A_5_5);

In [13]:
q

array([[-0.76076684, -0.48111549, -0.41139264,  0.13621311, -0.04431467],
       [-0.1121638 , -0.20431194,  0.45705464,  0.29459797,  0.80621896],
       [ 0.39018878,  0.07255761, -0.60201194,  0.67210254,  0.16836835],
       [-0.15080094,  0.44230361, -0.46783709, -0.51572309,  0.54477954],
       [-0.48338897,  0.72518096,  0.20141308,  0.42067314, -0.15137556]])

In [14]:
r

array([[-1.93779429, -0.29352551,  0.03285787, -0.23439462, -0.77033013],
       [ 0.        , -1.28022536,  1.29271333,  0.67927371,  1.00284384],
       [ 0.        ,  0.        , -0.66500257,  1.77916129, -1.44822011],
       [ 0.        ,  0.        ,  0.        , -1.55730703, -0.61144211],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.52379808]])

#Compute Sqaure Root of a Matrix

*   np.sqrt() function.


In [15]:
np.sqrt(np.arange(10))

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#Compute Exponential of each number of a Matrix.

*   np.exp() function



In [16]:
np.exp(np.arange(10))

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

#Find element-wise Maximum value by comparing 2 arrays.

*   np.maximun()



In [17]:
np.maximum(np.array([1,2,4]), np.array([3,1,1]))

array([3, 2, 4])

In [18]:
np.maximum(np.random.randn(3) , np.random.randn(3))

array([ 1.59121133,  0.93885358, -0.27365218])

#Segregate the Functional and Integral parts of a Floating Point Array.

*   np.modf() function.



In [19]:
decimal, whole = np.modf(np.random.randn(4))

In [20]:
decimal

array([-0.19508296, -0.9623875 ,  0.91805307,  0.00891835])

In [21]:
whole

array([-0., -0.,  1.,  1.])

##Vectorized version of Terniary Operation.

*   Vectorized version is similar to the List Comprehension.
*   np.where(condn arg , argument for TRUE , argument for FALSE)
*   Return elements chosen from x or y depending on condition.



In [22]:
np.where(np.array([True, False, False, True, False]), np.array([1.1, 1.2, 1.3, 1.4, 1.5]), np.array([2.1, 2.2, 2.3, 2.4, 2.5]))

array([1.1, 2.2, 2.3, 1.4, 2.5])

#Compute Mean Value across all elements of an Matrix.

*   np.mean() function
*   List item



In [23]:
np.mean(np.arange(10))

4.5

In [24]:
A_5_4 = np.random.randn(5,4) ; A_5_4

array([[-1.1074144 , -0.00505168, -0.76082919,  0.9480583 ],
       [-0.04413972,  0.76611587,  0.36840659,  0.37340862],
       [-0.34195859, -0.45682852, -0.31234129, -1.14138598],
       [ 0.90951723, -0.1977899 ,  1.20161786, -0.06752353],
       [ 1.14250133,  0.00737623, -0.26502569,  0.307339  ]])

In [25]:
np.mean(A_5_4)

0.0662026271098259

In [26]:
np.sum(A_5_4)

1.324052542196518

##Compute mean with respect to the 1st Dimension i.e *Column-wise MEAN*


In [27]:
#Column-wise Mean
np.mean(A_5_4, axis = 0)

array([0.11170117, 0.0227644 , 0.04636565, 0.08397928])

##Compute mean with respect to the 2nd Dimension i.e *Row-wise MEAN*

In [28]:
#Compute Row-wise Mean
np.mean(A_5_4, axis = 1)

array([-0.23130924,  0.36594784, -0.56312859,  0.46145542,  0.29804772])

##PSEUDO RANDOM NUMBER GENERATION

*   np.random.normal(size = (3,3)) -- Creates an array with the random nos from Normal DIstribution
*   If we do not specify any arguments then this function will also givee values from Standard Normal Distribution, just like the np.random.randn()



In [36]:
np.random.normal(size=(4,4))

array([[-0.06887369,  0.065263  ,  0.58022809, -0.77031685],
       [ 0.61398516, -0.50097301, -0.15368936, -0.55307523],
       [-0.08737009,  0.36909409, -0.0326722 ,  0.2280187 ],
       [-0.30306525,  0.15588668,  0.76912724, -1.26188502]])

##Setting Seed value to generate the same numbers using the Random function.

In [42]:
np.random.seed(108)
np.random.normal(size=(4,4))

array([[-1.02690451,  0.22174943,  1.13039011,  1.14618522],
       [-0.59273429,  0.11878403, -0.48443021, -1.94491271],
       [ 0.09207734,  0.90216909,  1.31446859,  0.77110218],
       [-0.54014736, -0.28411518, -0.88933117,  0.40416927]])