#NUMPY  PACKAGE AND ITS FUNCTIONALITY

In [85]:
import numpy as np

## n-Dimensional Array Object called "nD-Array"
### Its is a multidimensional container for elements of the same type.



In [86]:
##Creating 1D Array.
A_5 = np.array([1,2.1,3,4.3,5]); A_5

array([1. , 2.1, 3. , 4.3, 5. ])

In [87]:
##Creating 2D Array.
A_2_4 = np.array([[1,2,3,4],[1.1,2.2,3.3,4.4]]);A_2_4

array([[1. , 2. , 3. , 4. ],
       [1.1, 2.2, 3.3, 4.4]])

##Checking Array Attributes

*   ndim -- Checks for the dimensionality of the array, i.e 1d array or 2d array.
*   shape -- Checks for the number of rows and columns in the array.
*   dtype -- Checking the datatype of the array.
*   zeros -- Create an array of desired dimension(m*n) with elements as '0.0'
*   ones -- Create an array od desired dimension(m*n) with elements as '1.0'



In [88]:
A_5.ndim

1

In [89]:
A_2_4.ndim

2

In [90]:
A_5.shape

(5,)

In [91]:
A_2_4.shape

(2, 4)

In [92]:
A_5.dtype

dtype('float64')

In [93]:
A_2_4.dtype

dtype('float64')

In [94]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

##Casting the datatype of an Array from one type to another.

*   np.**astype**(np.datatype) -- Create a new array with the desired datatype by converting the datatype of the existing array elements.



In [97]:
A_4 = np.array([1,2,3,4], dtype = int) ; A_4

array([1, 2, 3, 4])

In [98]:
A_4.dtype

dtype('int64')

In [99]:
A_4.astype(np.int32)

array([1, 2, 3, 4], dtype=int32)

In [100]:
A_2_2 = np.array([[1,2],[3,4]], dtype=np.int16); A_2_2

array([[1, 2],
       [3, 4]], dtype=int16)

In [101]:
#Converting the integer to float datatype of a np array.
A_2_2.astype(np.float16)

array([[1., 2.],
       [3., 4.]], dtype=float16)

In [102]:
#Converting the string to float datatype of a np array.
A_2_2 = np.array([['1.1','2.2'],['3.3','4.4']], dtype=np.str0); A_2_2

array([['1.1', '2.2'],
       ['3.3', '4.4']], dtype='<U3')

In [103]:
A_2_2.astype(np.float16)

array([[1.1, 2.2],
       [3.3, 4.4]], dtype=float16)

##Use another array datatype to convert the datatype of the array elements.

In [104]:
A_5

array([1. , 2.1, 3. , 4.3, 5. ])

In [105]:
A_5.astype(A_4.dtype) ## Converted the float array A_5 to an integer array using the datatype of A_4 integer array.

array([1, 2, 3, 4, 5])

#Perform Arithmatic operations and access elements of Numpy Arrays.

In [106]:
A_2_4 = np.array([[1,2,3,4],[1.1,2.2,3.3,4.4]]); A_2_4

array([[1. , 2. , 3. , 4. ],
       [1.1, 2.2, 3.3, 4.4]])

In [107]:
A_2_4 * A_2_4

array([[ 1.  ,  4.  ,  9.  , 16.  ],
       [ 1.21,  4.84, 10.89, 19.36]])

In [108]:
A_2_4 - A_2_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
A_2_4 ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.04880885, 1.4832397 , 1.81659021, 2.0976177 ]])

In [110]:
A_2_4 == A_2_4

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
1/A_2_4

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.90909091, 0.45454545, 0.3030303 , 0.22727273]])

##Accessing Array elements by Indexing...

In [112]:
  A_2_4

array([[1. , 2. , 3. , 4. ],
       [1.1, 2.2, 3.3, 4.4]])

###Accessing the rows of a 2D matrix.

In [113]:
A_2_4[0]

array([1., 2., 3., 4.])

In [114]:
A_2_4[1]

array([1.1, 2.2, 3.3, 4.4])

##Accessing the elements of the n-Dimensional matrix

*   #basicform: - [1st dim index, 2nd dim index, 3rd dim index, 4th dim index...]



In [115]:
##Accessing the elements of the 2D matrix
A_2_4[0,1]

2.0

In [116]:
A_2_4[1,1]

2.2

##Slicing an Array

In [117]:
A_5

array([1. , 2.1, 3. , 4.3, 5. ])

In [118]:
A_5[2:4]

array([3. , 4.3])

## NOTE:: If we modify the values of the sliced array, then the changes will reflect in the main array.

* So essentially slices are more like views and not copies.

In [119]:
A_5

array([1. , 2.1, 3. , 4.3, 5. ])

In [120]:
A_5[2:4] = 1.5 ; A_5

array([1. , 2.1, 1.5, 1.5, 5. ])

In [121]:
L = [1,2.1,3,4.3,5]; L

[1, 2.1, 3, 4.3, 5]

In [122]:
L[2:4]

[3, 4.3]

In [123]:
L[2:4] = [3.8,3.8]; L

[1, 2.1, 3.8, 3.8, 5]

##Using Array slicing for Initialisation effect.

In [124]:
A_5

array([1. , 2.1, 1.5, 1.5, 5. ])

In [125]:
A_5[:] = 1.0; A_5

array([1., 1., 1., 1., 1.])

##Another way to access the elements of the multi-dimensional array.

*   basic form: - [1st dimension index][2nd dimension index][3rd dimension index]

In [126]:
A_2_2_3 = np.array([ 
                      [ 
                        [1,2,3] 
                       ] 
                    , [ 
                        [4,5,6] 
                       ] 
    ])

In [127]:
A_2_2_3.shape

(2, 1, 3)

In [128]:
A_2_2_3 = np.array([[ [1,2,3] , [4,5,6] ] , [ [7,8,9] , [10,11,12] ]]); A_2_2_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [129]:
A_2_2_3[1,1,2]

12

In [130]:
A_2_2_3[1,1,2]

12

#ADDITIONAL ARRAY OPERATIONS

* Additional ways to create Numpy Arrays
* Apply Filter to the Numpy array
* How to Dice Numpy array
* Take backup of Numpy array.


## Creating Array by the combination of the *arange()* and the *reshape()* function.

In [131]:
# Creating Array by the combination of the arange() and the reshape() function.
np.arange(5,20,0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [132]:
np.arange(5,20,0.5).shape

(30,)

In [133]:
np.arange(5,20,0.5).reshape(5,6)

array([[ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. , 10.5],
       [11. , 11.5, 12. , 12.5, 13. , 13.5],
       [14. , 14.5, 15. , 15.5, 16. , 16.5],
       [17. , 17.5, 18. , 18.5, 19. , 19.5]])

In [134]:
# 2nd example -- Create a 2D array using the same approach

A_8_4 = np.arange(32).reshape((8,4)); A_8_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# TO CREATE ARRAY OF RANDOMLY GENERATED DATA AND NORMALLY DISTRIBUTED DATA FOR INITIALIZATION OF VALUES , USE random.randn() function.

In [135]:
# Create a random 2D array with values that follows Normal distribution.
np.random.randn(5,3)

array([[-0.54342185, -0.55719065, -0.07864839],
       [-1.12922228,  0.06965066, -0.31067025],
       [-0.21619752, -0.54920995, -0.19093203],
       [ 0.90972761, -2.80312615, -1.4554176 ],
       [-0.31951647,  1.27034797,  0.3857522 ]])

# FANCY INDEXING
##ARRAY Filtering and Dicing using Fancy Indexing

*   Basic Form: [[1st dim]] [:,[2nd]] [:,:,[3rd]]
*   Incase some dimensions are not needed then they can be Omitted, all the elements for the Omitted dimension can be selected.



In [136]:
A_8_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

##To Select Rows from a 2D Array, specify the desired Indexes for 1st dimension

In [137]:
#Slice the Array to Select the row 1,3,5 from the Array.

A_8_4[[1,3,5]]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

##To Select columns from a 2D Array, specify the desired Indexes for 2nd dimension

In [138]:
A_8_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [139]:
#Slice the Array to select the 1st and 3rd COLUMNS
A_8_4[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23],
       [25, 27],
       [29, 31]])

## Similarly Select both ROWS and COLUMNS in 2D Array

In [145]:
#Select both rows and cols in 2D Array
A_8_4[[1,3,5]][:,[1,3]]


array([[ 5,  7],
       [13, 15],
       [21, 23]])

##TAKING A BACKUP OF AN ARRAY USING THE COPY METHOD

In [146]:
A_2_2_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [153]:
A_2_2_3_back0 = A_2_2_3[[0]].copy() ; A_2_2_3_back0

array([[[1, 2, 3],
        [4, 5, 6]]])